name: concessionario_supercar
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.0
  google_maps_flutter: ^2.6.1
  geolocator: ^14.0.1
  sensors_plus: ^6.0.1
  http: ^1.2.2
  shared_preferences: ^2.3.2
  webfeed: ^0.7.0
  palette_generator: ^0.3.3+2
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    # Macchine
    - assets/supercar.jpg
    - assets/ferrari.jpg
    - assets/lamborghini.jpg
    - assets/mclaren.jpg
    - assets/bugatti.jpg
    - assets/cars.json
    - assets/Ferrari_250_GTO.png 
    - assets/porsche.jpg
    - assets/rolls_royce.jpg
    - assets/aston_martin.jpg
    - assets/maserati.jpg
    - assets/bentley.jpg
    - assets/koenigsegg.jpg
    - assets/pagani.jpg
    - assets/jaguar.jpg
    - assets/lotus.jpg

    # Loghi macchine
    - assets/loghi/bugatti_logo.png
    - assets/loghi/ferrari_logo.png
    - assets/loghi/lamborghini_logo.png
    - assets/loghi/mclaren_logo.png
    - assets/loghi/porsche_logo.png
    - assets/loghi/rolls_royce_logo.png
    - assets/loghi/aston_martin_logo.png
    - assets/loghi/maserati_logo.png
    - assets/loghi/bentley_logo.png
    - assets/loghi/koenigsegg_logo.png
    - assets/loghi/pagani_logo.png
    - assets/loghi/jaguar_logo.png
    - assets/loghi/lotus_logo.png 