name: concessionario_supercar
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.0
  google_maps_flutter: ^2.6.1
  geolocator: ^14.0.1
  sensors_plus: ^6.0.1
  http: ^1.2.2
  shared_preferences: ^2.3.2
  webfeed: ^0.7.0
  palette_generator: ^0.3.3+2
  google_fonts: ^6.1.0
  carousel_slider: ^5.1.1
  video_player: ^2.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    #contiene tutti i loghi
    - assets/loghi/
    #contiene le immagini di presentazione delle auto
    - assets/macchine/
    #contiene le singole auto per brand
    - assets/macchine_per_brand/  
    #contiene i video per i brand
    - assets/video/
    #luoghi concessionari
    - assets/dealers.json
    #info auto
    - assets/cars.json