name: concessionario_supercar
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.0
  google_maps_flutter: ^2.6.1
  geolocator: ^14.0.2
  sensors_plus: ^6.0.1
  http: ^1.2.2
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/supercar.jpg
    - assets/ferrari_offer.jpg
    - assets/ferrari.jpg
    - assets/lamborghini.jpg
    - assets/mclaren.jpg
    - assets/bugatti.jpg
    - assets/cars.json