name: Flutter CI

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  lint-and-tests:
    name: Analyze + Unit/Widget tests + Integration + Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.0"
          channel: "stable"
          cache: true

      - name: Flutter pub get
        run: flutter pub get

      - name: Analisi statica
        run: flutter analyze --no-fatal-infos --no-fatal-warnings

      - name: Unit + Widget tests (headless)
        run: xvfb-run -a flutter test --no-pub --exclude-tags native

      - name: Integration tests (headless)
        run: xvfb-run -a flutter test --no-pub integration_test

      - name: Install Android SDK 35
        run: |
          yes | ${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager "platforms;android-35" "build-tools;35.0.0"

      - name: Build APK release
        run: flutter build apk --release

      - name: Upload artifact (APK)
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk