name: Flutter CI

on:
  push:
    branches: [ "main", "Branch2" ]
  pull_request:
    branches: [ "main", "Branch2" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Flutter version
        run: flutter --version

      - name: Install Flutter dependencies
        run: flutter pub get

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y ninja-build libgtk-3-dev xvfb

      - name: Analyze
        run: flutter analyze

      - name: Run unit & widget tests
        run: flutter test

      - name: Run integration tests
        run: xvfb-run -s "-screen 0 1600x1200x24" flutter test integration_test

      - name: Build Android APK (release)
        if: ${{ success() }}
        run: flutter build apk --release

      - name: Upload APK artifact
        if: ${{ success() }}
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
