name: Flutter CI

on:
  push:
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      
uses: actions/checkout@v4
uses: subosito/flutter-action@v2
    with:
      flutter-version: "3.24.0"
run: flutter pub get
name: Analisi statica
run: flutter analyze
name: Test (unit + widget)
run: flutter test --no-pub
name: Integration tests (headless)
run: flutter test integration_test --no-pub
name: Build APK release
run: flutter build apk --release
name: Artifact APK
uses: actions/upload-artifact@v4
with:
  name: app-release-apk
  path: build/app/outputs/flutter-apk/app-release.apk