name: Flutter CI

on:
  push:
    branches: [ "main", "Branch2" ]
  pull_request:
    branches: [ "main", "Branch2" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout
        uses: actions/checkout@v4

      # Step 2: Setup Java (per Android build)
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # Step 3: Setup Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Flutter version
        run: flutter --version

      # Step 4: Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Step 5: Static analysis
      - name: Analyze
        run: flutter analyze

      # Step 6: Run unit & widget tests
      - name: Run unit & widget tests
        run: flutter test

      # Step 7: Run integration tests (Web / Chrome in headless mode)
      - name: Run integration tests (Chrome)
        run: |
          sudo apt-get update && sudo apt-get install -y ninja-build libgtk-3-dev xvfb libglu1-mesa
          xvfb-run -s "-screen 0 1600x1200x24" flutter drive \
            --driver=test_driver/integration_test.dart \
            --target=integration_test/app_test.dart \
            -d chrome

      # Step 8: Build Android APK (release)
      - name: Build Android APK (release)
        if: ${{ success() }}
        run: flutter build apk --release

      # Step 9: Upload APK artifact
      - name: Upload APK artifact
        if: ${{ success() }}
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
