name: Flutter CI

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  lint-tests-build:
    name: Analyze + Unit/Widget + Integration (Linux) + Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java (JDK 17)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.0"
          channel: "stable"
          cache: true

      - name: Flutter pub get
        run: flutter pub get

      - name: Analisi statica
        run: flutter analyze --no-fatal-infos --no-fatal-warnings

      - name: Unit + Widget tests
        run: xvfb-run -a flutter test --no-pub --exclude-tags native

      - name: Disable web
        run: flutter config --no-enable-web

      - name: Enable Linux desktop
        run: flutter config --enable-linux-desktop

      - name: Install Xvfb
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb

      - name: Integration tests (Linux desktop)
        run: xvfb-run -a flutter test -d linux integration_test/app_start_test.dart --no-pub

      - name: Install Android SDK 36
        run: |
          yes | ${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager "platforms;android-36" "build-tools;36.0.0"

      - name: Build APK release
        run: flutter build apk --release

      - name: Upload artifact (APK)
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk