name: Flutter CI

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  lint-and-tests:
    name: Analyze + Unit/Widget tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.0"
          channel: "stable"
          cache: true

      - name: Flutter pub get
        run: flutter pub get

      - name: Analisi statica
        run: flutter analyze --no-fatal-infos --no-fatal-warnings

      - name: Unit + Widget tests (headless)
        run: xvfb-run -a flutter test --no-pub --exclude-tags native

      - name: Install Android SDK 35
        run: |
          yes | ${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager "platforms;android-35" "build-tools;35.0.0"

      - name: Build APK release
        run: flutter build apk --release

      - name: Upload artifact (APK)
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk

  # --- Job dedicato ai test di integrazione che usano plugin nativi ---
  integration-android:
    runs-on: ubuntu-latest
    timeout-minutes: 40

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java (JDK 17)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.0"
          channel: "stable"
          cache: true

      - name: Flutter pub get
        run: flutter pub get

      - name: Install Android SDK 35
        run: |
          yes | ${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager "platforms;android-35" "build-tools;35.0.0"

      # Pre-build per scaldare la cache gradle/AGP
      - name: Warm up Gradle / Build debug
        run: flutter build apk --debug

      - name: Run integration tests on Android emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 33
          arch: x86_64
          profile: pixel_5
          emulator-options: -no-snapshot -no-window -gpu swiftshader_indirect
          script: |
            set -euxo pipefail
            flutter doctor -v
            flutter devices

            if [ -d "integration_test" ]; then
              if [ -f "test_driver/integration_test.dart" ]; then
                DEFAULT_TARGET=$(ls integration_test | head -n1)
                if [ -z "$DEFAULT_TARGET" ]; then
                  echo "Nessun file in integration_test/ trovato"
                  exit 1
                fi
                echo "Eseguo flutter drive su: integration_test/$DEFAULT_TARGET"
                flutter drive \
                  --driver=test_driver/integration_test.dart \
                  --target=integration_test/$DEFAULT_TARGET \
                  -d emulator-5554
              else
                echo "Eseguo flutter test -d emulator-5554 integration_test"
                flutter test -d emulator-5554 integration_test
              fi
            else
              echo "Nessuna cartella integration_test/ presente: salto gli integration test."
            fi

      - name: Build APK (release)
        run: flutter build apk --release

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk